### ISSUE TITLE
How to custom button label "Previous" and "Next"

### ISSUE THREAD

**Issue by Anricx** [Ynjxsjmh/gitbook-plugin-bottom-navigation#1]
How to custom button label "Previous" and "Next"

**Comment by Ynjxsjmh** [comment]
Don't understand, you want to change `Previous` to some description else?

**Comment by Ynjxsjmh** [comment]
If so, it is not currently supported by setting properties directly, but you can change it in source file directly

https://github.com/Ynjxsjmh/gitbook-plugin-bottom-navigation/blob/bcc04a21967b3715dbc6e22416c30e5832fa8380/book/plugin.js#L17

**Comment by Ynjxsjmh** [comment]
New version 0.2.2 is published, you can now customize it with `prevText` and `nextText`.
